package.json
src/index.js
test/index.spec.js

keys used for datastore must use the `interface-datastore` for being created.
For reference:
https://github.com/ipfs/go-ipfs/blob/master/namesys/publisher.go#L56

fix: local key for datastore

---

README.md

This is just a small tweak to the text of the licensing section in the README. It should help it read a little bit clearer.

Make small fix to license text in README

---

src/index.js
test/index.spec.js

For the first step of `ipns working locally`, the records needed to be stored using `base32(/ipns/{cid})`, in order to guarantee interop with `go-ipfs`. 
However, integrating the DHT with `ipfs`, the `dht` will be responsible for the `base32` operation, as it does for all records stored in it, which in this case would end up on `base32(base32(/ipns/{cid}))`.
Accordingly, a new ID key was added (`routingKey`), which should be used for the routing part of `IPNS`. After this got released, the `ipnsKey` will not be needed anymore.

feat: add routing id key

---

.gitignore
README.md
src/index.js
test/index.spec.js

`ipns` should offer a validator capable of validate records, as well select which one is the best record between two of them (using the sequence number).
This is particularly useful for validating libp2p records transparently, providing this validator.
Note: `go-ipns` also provides this feature [here](https://github.com/ipfs/go-ipns/blob/d5f9cadbca0a3de92ee17a5810a4ea50c6e514ce/record.go#L26)

feat: add records validator

---

src/index.js
test/index.spec.js

This allows two `createWithExpiration` to have the same return value without mocking the global `require('nano-date')`

feat: prevent side effect on `create`

---

README.md
src/index.js
test/index.spec.js

Since `libp2p-record` does not have author (removed for interop with `go-ipfs`), `validateRecord` must find the peerId, using the key (`/ipns/{peer_id}`)
BREAKING CHANGE: having the libp2p-record protobuf definition compliant with go-libp2p-record. Author and signature were removed.

fix: validator should create peer id

---

package.json
src/index.js

We are having multiple versions of `peer-id` in the `js-ipfs` bundle

chore: upgrade dependencies

---

src/index.js
test/index.spec.js

Running my local js-ipfs daemon it crashed when running the IPNS validator. Currently if the validator runs and cannot get an embedded public key it will attempt to use the public key of the peer. However, the validator doesn't have access to the peer public key, as it creates the peerId from bytes.
I'm not very familiar with the IPNS code base so there may be a better way to resolve this. This simply ensures that `extractPublicKey` actually returns a key.

fix: verify public key exists in validator

---

package.json
src/utils.js

left-pad is deprecated in favor of String.prototype.padStart()

fix: remove leftpad

---

package.json
src/index.js
test/index.spec.js

Needed to upgrade `ipfs` to the latest `libp2p`, otherwise you end up with multiple versions of `peer-id` in the dependency tree and then libp2p thinks peer-ids are not peer-ids and can't dial anything.
Depends on libp2p/js-libp2p-crypto#158

chore: downgrade peer-id to the same version used by libp2p

---

.travis.yml
package.json

Remove unused `left-pad` dependency from `package.json`.

fix: Remove unused left-pad

---

src/index.js
test/index.spec.js

The boolean argument to `new Key` specifies whether to try to clean the key up - remove trailing slashes, etc.
Here we're putting potentially non-printable characters into the key so we don't want to do any such operation.
fixes ipfs/js-ipfs#2930

fix: key encoding

---

.aegir.js
README.md
package.json
src/index.js
test/index.spec.js

BREAKING CHANGES:
- All deps of this module use Uint8Arrays instead of Buffers
- value and validity fields of IPNSEntries are now Uint8Arrays instead
of Strings as they are `bytes` in the protobuf definition

fix: replace node buffers with uint8arrays

---

.aegir.js
.travis.yml
package.json

Updates dev dependencies `ipfsd-ctl` + `ipfs` and changes CI's node versions as hapi dropped support for node < 12
Closes #69 and #71

chore: update deps

---

package.json

Otherwise the dist folder doesn't get published since it's in the `.gitignore` file.
`npm pack` before:
```
npm notice 📦  ipns@0.9.0
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 508B   src/errors.js
npm notice 11.9kB src/index.js
npm notice 9.6kB  test/index.spec.js
npm notice 12.9kB src/pb/ipns.js
npm notice 1.5kB  src/utils.js
npm notice 2.4kB  package.json
npm notice 203B   tsconfig.json
npm notice 7.6kB  CHANGELOG.md
npm notice 650B   .github/ISSUE_TEMPLATE/open_an_issue.md
npm notice 7.6kB  README.md
npm notice 639B   src/pb/ipns.proto
npm notice 2.8kB  src/pb/ipns.d.ts
npm notice 412B   src/types.d.ts
npm notice 946B   .travis.yml
npm notice 2.9kB  .github/config.yml
npm notice 311B   .github/ISSUE_TEMPLATE/config.yml
npm notice === Tarball Details === …
```

fix: add files list to package.json

---

src/index.js
test/index.spec.js

We accept strings as values to publish, but the actual datatype is Uint8Array.  Likewise these Uint8Arrays get turned into strings when passed back, but in JavaScript this can be a lossy translation as bytes values above 127 are interpreted as multi-byte UTF8 code points.
This PR removes strings as acceptable input types and only accepts Uint8Arrays.
It also demands record TTLs be numbers and not strings.
BREAKING CHANGE: strings are no longer accepted as valid values to publish or for ttls, use Uint8Arrays and numbers instead

fix: remove value ambiguity

---

src/index.js
test/index.spec.js

Use `uint8ArrayToString` instead of calling `.toString()` on the Uint8Array instance directly.

fix: encode ipns key correctly

---

package.json
test/index.spec.js

As of `aegir@33.1.0`, `chai-string` and `chai-bytes` are bundled with
aegir so no need to depend on them separately.

chore: remove chai deps

---

src/index.js
test/index.spec.js
tsconfig.json

BREAKING CHANGE: ipns validate function returns a void promise instead of boolean promise

fix: ipns validate should return void

---

package.json

Demand a version that depends on ipfs-utils@8.x

chore: update interface datastore

---

src/index.js
test/index.spec.js

Peer IDs are sent as a buffer containing the utf bytes for `/ipns/`
then the bytes that make up the peer id.
Our tests were using a buffer that contained the utf bytes for `/ipns/`
followed by the utf bytes for the base encoded peer id, which is wrong.
I think this only worked previously because the validator passed the
bytes to `PeerId.createFromBytes` which passes them to the `cids` `CID`
class constructor which is a lot more forgiving in terms of input than
the multiformats `CID` class.

fix: parse peer id from message correctly

---

src/index.js

go-ipfs expects keys to be in PascalCase not camelCase.

fix: cbor keys should be pascal case

---

src/utils.ts

Protobufjs returns bigints as numbers.  Can be reverted by switching to protons.

fix: ensure bigints are bigints

---

README.md
src/index.ts
src/validator.ts
test/index.spec.ts

This is part of deprecation described in https://github.com/ipfs/js-ipfs/issues/4197
- record `ipns.create` continues to create records with both V1 and V2  signatures
- record `ipns.validate` no longer accepts V1 signatures
Meaning:
- modern nodes are 100% V2, they ignore V1 signatures
- legacy nodes (go-ipfs < v0.9.0, js-ipfs before Jun 2021) are still able to resolve names created by js-ipns, because V1 is still present

fix!: require V2 signatures

---

package.json

The CID class in multiformats v11.x.x shipped with a breaking change so update all deps to use the latest version.

deps!: update multiformats to v11

---

src/index.ts
src/utils.ts
test/index.spec.ts

This module has accepted `Uint8Array`s as values to store in IPNS
records which means it has been mis-used to create records with
raw CID bytes.
To ensure this doesn't happen in future, accept only CIDs, PeerIds
or arbitrary path strings prefixed with `"/"`.

fix!: only accept CIDs, PeerIds or strings as values

---

src/index.ts

Allows passing an options object with an optional `v1Compatible` field.

fix: add extra signature for empty options object

---

.aegir.js
package.json

[Tree shaking](https://webpack.js.org/guides/tree-shaking/) results in smaller web bundles by deleting unused code.
This module is side-effect free so mark it as such to signal to bundlers that unused exports can be excluded from bundles.

fix: mark package as side-effect free

---

src/validator.ts

The value field is a string so it needs to be logged as `%s` - logging as `%b` will throw.

fix: log type as string

---

README.md
package.json
src/errors.ts
src/index.ts
src/pb/ipns.ts
src/selector.ts
src/utils.ts
src/validator.ts
test/conformance.spec.ts
test/index.spec.ts
test/selector.spec.ts
test/utils.spec.ts
test/validator.spec.ts

- Updates method names so they can be invidually imported but still be legible
- Operates on PrivateKey/PublicKeys instead of PeerIds to integrate with the libp2p@2.x.x keychain will less friction
BREAKING CHANGE: uses libp2p@2.x.x deps, operates on PrivateKey/PublicKeys instead of PeerIds

fix!: update to libp2p@2.x.x deps

---

README.md
src/index.ts
src/selector.ts
src/validator.ts
test/utils.spec.ts

- **test: clarify that paths are allowed with test**
- **docs: update based on curent API**

docs: update api docs
